In [3]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [4]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [5]:
b = np.arange(24)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [6]:
c = b.reshape(2,4,3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [7]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [10]:
v = np.linspace(10, 20, 5, endpoint=False)
print(v)

[10. 12. 14. 16. 18.]


In [12]:
f = np.logspace(1.0, 2.0, num=10, base=2)
print(f)

[2.         2.16011948 2.33305808 2.5198421  2.72158    2.93946898
 3.1748021  3.42897593 3.70349885 4.        ]


In [15]:
y = np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
s = slice(2, 7, 2)
print(y[s])

[2 4 6]


In [17]:
g = y[2:7:2]
print(g)

[2 4 6]


In [19]:
print(y[2:5])

[2 3 4]


In [20]:
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(a[0:2])

[[1 2 3]
 [4 5 6]]


In [27]:
b = a[[0,1,2], [0,1,0]]
print(b)

[1 5 7]


In [28]:
x = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [30]:
row = np.array([[0,0], [3,3]])
cols = np.array([[0,2], [0,2]])
y = x[row, cols]
print(y)

[[ 0  2]
 [ 9 11]]


In [31]:
print(x[x>5])

[ 6  7  8  9 10 11]


In [32]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

[ 10  40  90 160]


In [33]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,2,3])
print(a+b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [34]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [35]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55
